name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - ci-scripts
jobs:
  x86_64-linux-debug:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/12202441821c4e916ab128580655d8189610ca66c85fcc2545629c509e211cc88f8f/bin/zig build --maxrss 21000000000 -Dbuild-type=Debug -Dextra-target=arm-linux-musleabihf cmake-bootstrap tidy update-stage1
  x86_64-linux-release:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/12202441821c4e916ab128580655d8189610ca66c85fcc2545629c509e211cc88f8f/bin/zig build --maxrss 21000000000 -Dbuild-type=Release -Dextra-target=arm-linux-musleabihf -Dcc=cc cc-bootstrap cmake-bootstrap tidy reproducible update-stage1
  aarch64-linux-debug:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/122007c945ba64a5103b6ee10455c7e6b89d8d5de5887034df5b9d1b5c1dc8a0a4c1/bin/zig build --maxrss 24696061952 -Dbuild-type=Debug -Dextra-target=arm-linux-musleabihf cmake-bootstrap tidy update-stage1
  aarch64-linux-release:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Linux, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/122007c945ba64a5103b6ee10455c7e6b89d8d5de5887034df5b9d1b5c1dc8a0a4c1/bin/zig --maxrss 24696061952 -Dbuild-type=Release -Dextra-target=arm-linux-musleabihf cmake-bootstrap tidy reproducible update-stage1
  x86_64-macos-debug:
    if: github.repository_owner == 'ziglang'
    runs-on: "macos-11"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Package Cache
        id: package-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/zig
          key: x86_64-macos-package-${{hashFiles('ci/build.zig.zon')}}
          restore-keys: x86_64-macos-package-
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/1220451d009ecda5092b59835ba65ea5d5ca04046436aab6f2fd113c00c7e794b860/bin/zig build -Dbuild-type=Debug -Dskip-non-native cmake-bootstrap tidy update-stage1
      - name: Save Package Cache
        if: steps.package-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/zig
          key: ${{steps.package-cache.outputs.cache-primary-key}}
  x86_64-macos-release:
    if: github.repository_owner == 'ziglang'
    runs-on: "macos-11"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Package Cache
        id: package-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/zig
          key: x86_64-macos-package-${{hashFiles('ci/build.zig.zon')}}
          restore-keys: x86_64-macos-package-
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/1220451d009ecda5092b59835ba65ea5d5ca04046436aab6f2fd113c00c7e794b860/bin/zig build -Dbuild-type=Release -Dcc=cc -Dskip-non-native cc-bootstrap cmake-bootstrap tidy reproducible update-stage1
      - name: Save Package Cache
        if: steps.package-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/zig
          key: ${{steps.package-cache.outputs.cache-primary-key}}
  aarch64-macos-debug:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, macOS, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/1220c6e8b6fd8eb397a8e54139ae0baec6583a7f72e509623437ff255ebc278822a1/bin/zig build -Dbuild-type=Debug -Dskip-non-native cmake-bootstrap tidy update-stage1
  aarch64-macos-release:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, macOS, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: $HOME/.cache/zig/p/1220c6e8b6fd8eb397a8e54139ae0baec6583a7f72e509623437ff255ebc278822a1/bin/zig build -Dbuild-type=Release -Dskip-non-native cmake-bootstrap tidy reproducible update-stage1
  x86_64-windows-debug:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Windows, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: '& $Env:USERPROFILE\AppData\Local\zig\p\12204a122b74c73de3b84d0626b99a5e355a037fc7b1c8ffa14c9d7bdc2e9a40d3d3\bin\zig.exe build -Dbuild-type=Debug -Dskip-non-native cmake-bootstrap tidy update-stage1 msvc'
  x86_64-windows-release:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Windows, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: '& $Env:USERPROFILE\AppData\Local\zig\p\12204a122b74c73de3b84d0626b99a5e355a037fc7b1c8ffa14c9d7bdc2e9a40d3d3\bin\zig.exe build -Dbuild-type=Release -Dskip-non-native cmake-bootstrap tidy update-stage1 msvc' # reproducible
  aarch64-windows-release:
    if: github.repository_owner == 'ziglang'
    runs-on: [self-hosted, Windows, aarch64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build and Test
        working-directory: ci
        run: '& $Env:USERPROFILE\AppData\Local\zig\p\1220f756f38997a4f89d620aa77a2db21463ed7cc2dff5574e835894bb1969dfca95\bin\zig.exe build -Dbuild-type=Release -Dskip-non-native cmake-bootstrap tidy' # reproducible
